import type { Metadata } from "next";
import Image from "next/image";
import { ReactNode } from 'react';

import { steps } from "./constants";

export const metadata: Metadata = {
  title: "Mikkoapp | Criando seu ",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
  params: Promise<{ step: string }>;
};

export default async function OnboardingLayout({ children, params }: LayoutProps) {
  const { step } = await params;

  const currentStep = steps.find(s => s.name === step) || steps[0];

  const progressWidth = (currentStep?.position / steps.length) * 100;

  return (
    <>
      <div className="w-full h-[6px] bg-[#EBEBEB]">
        <div className={`h-full bg-secondary`} style={{ width: `${progressWidth}%` }} />
      </div>

      <div className="h-full px-6 py-12 flex flex-col max-w-[600px] mx-auto">
        <header className="flex flex-col gap-5">
          <Image src="/logo.svg" alt="Mikkoapp logo" width={85} height={23} />
          <div className="flex flex-col gap-2">
            <span className="text-[#666666] text-xs">Passo {currentStep?.position} de {steps.length}</span>
            <h1
              className="w-full max-w-[345px] text-dark text-2xl font-semibold"
              dangerouslySetInnerHTML={{
                __html: currentStep?.title
                  .replace(/\[(.*?)\]/g, '<strong class="text-secondary">[$1]</strong>')
                  .replace(/\[|\]/g, '')
              }}
            />
          </div>
        </header>

        <main className="h-full overflow-y-auto">
          {children}
        </main>
      </div>
    </>
  );
}
