import type { Metadata } from "next";
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: "Mikkoapp | Descomplicando a sua vida",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
  params: Promise<{ step: string }>;
};

export default async function LoginLayout({ children }: LayoutProps) {
  return (
    <>
      {children}
    </>
  );
}
