import type { Metadata } from "next";
import { Rubik, Red_Hat_Display } from "next/font/google";

import './globals.css';

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mikkoapp | Planejador Financeiro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${redHatDisplay.variable} antialiased h-[100vh]`}
      >
        {children}
      </body>
    </html>
  );
}
