import { ReactNode } from 'react';
import Image from "next/image";
import type { Metadata } from "next";

import { MobileNavbar } from '@/components/dashboard/mobile-navbar';

export const metadata: Metadata = {
  title: "Mikkoapp | Descomplicando a sua vida",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
  params: Promise<{ step: string }>;
};

export default async function ExtractLayout({ children }: LayoutProps) {
  return (
    <div className="w-screen h-screen bg-dashboardBg">
      <div className="mx-auto h-full w-full px-5 overflow-hidden flex flex-col">
        <div className="absolute top-0 right-2">
          <Image src="/mikko-tail-light-2.svg" alt="Mikko tail" width={200} height={230} />
        </div>
        {children}
      </div>

      <MobileNavbar />
    </div>
  );
}
